/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import controller.PembayaranController;
import java.io.File;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JRViewer;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Toshiba
 */
public class ViewLaporanPembayaran extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewLaporanPembayaran
     */
    private String header[] = {" NIK ", " Nama Nasabah ", " Kode ASuransi ", " Jenis Asuransi ", "Tanggal Bayar"};
    public PembayaranController pc;

    public ViewLaporanPembayaran() {
        initComponents();
        
         pc = new PembayaranController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCari = new javax.swing.JTextField();
        btn_lapPembayaran = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Laporan Pembayaran");

        btn_lapPembayaran.setText("Cetak Laporan");
        btn_lapPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lapPembayaranActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_lapPembayaran)
                        .addGap(0, 321, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_lapPembayaran))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_lapPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lapPembayaranActionPerformed
        // TODO add your handling code here:
        if (txtCari.getText().equals("")) {
            try {
                String path = "report/ReportPembayaranWithoutWhere.jasper";
            String driver="oracle.jdbc.OracleDriver";
            String konek="jdbc:oracle:thin:@localhost:1521:XE";
            String user="system";
            String password="root";
            HashMap parameter = new HashMap();
            Class.forName(driver);
            Connection conn = DriverManager.getConnection(konek,user,password);
            File reportFile=new File(path);
//            parameter.put("no_polis", txtCari.getText());
            InputStream jReport = this.getClass().getClassLoader().getResourceAsStream(reportFile.getPath());
//            JasperReport jReport = (JasperReport) JRLoader.loadObjectFromFile(reportFile.getPath());
//            JasperPrint jPrint = JasperFillManager.fillReport(jReport, parameter, conn);
            JasperPrint jp = JasperFillManager.fillReport(jReport, parameter, conn);
//            JasperViewer.viewReport(jPrint, true);
//            JasperViewer viewer = new JasperViewer(jPrint);
//            JasperViewer.setDefaultLookAndFeelDecorated(true);
//            cr.add(viewer);
//            cr.show();
            JRViewer jViewer = new JRViewer (jp);
            jViewer.setVisible(true);
            jViewer.setOpaque(true);
            jScrollPane2.add(jViewer);
            jScrollPane2.setViewportView(jViewer);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Laporan Tidak Dapat Dicetak!\n" + e.getMessage()
                ,"Cetak Laporan", JOptionPane.ERROR_MESSAGE);
        }
        }else{
        try {
                String path = "report/ReportPembayaran.jasper";
            String driver="oracle.jdbc.OracleDriver";
            String konek="jdbc:oracle:thin:@localhost:1521:XE";
            String user="system";
            String password="root";
            HashMap parameter = new HashMap();
            Class.forName(driver);
            Connection conn = DriverManager.getConnection(konek,user,password);
            File reportFile=new File(path);
            parameter.put("no_polis", txtCari.getText());
            InputStream jReport = this.getClass().getClassLoader().getResourceAsStream(reportFile.getPath());
//            JasperReport jReport = (JasperReport) JRLoader.loadObjectFromFile(reportFile.getPath());
//            JasperPrint jPrint = JasperFillManager.fillReport(jReport, parameter, conn);
            JasperPrint jp = JasperFillManager.fillReport(jReport, parameter, conn);
//            JasperViewer.viewReport(jPrint, true);
//            JasperViewer viewer = new JasperViewer(jPrint);
//            JasperViewer.setDefaultLookAndFeelDecorated(true);
//            cr.add(viewer);
//            cr.show();
            JRViewer jViewer = new JRViewer (jp);
            jViewer.setVisible(true);
            jViewer.setOpaque(true);
            jScrollPane2.add(jViewer);
            jScrollPane2.setViewportView(jViewer);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Laporan Tidak Dapat Dicetak!\n" + e.getMessage()
                ,"Cetak Laporan", JOptionPane.ERROR_MESSAGE);
        }    
        }
        
    }//GEN-LAST:event_btn_lapPembayaranActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_lapPembayaran;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
