/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import controller.PembayaranController;
import java.io.File;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Toshiba
 */
public class ViewLaporanPembayaran extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewLaporanPembayaran
     */
    private String header[] = {" NIK ", " Nama Nasabah ", " Kode ASuransi ", " Jenis Asuransi ", "Tanggal Bayar"};
    public PembayaranController pc;

    public ViewLaporanPembayaran() {
        initComponents();
        
         pc = new PembayaranController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbCari = new javax.swing.JComboBox<>();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLapPemb = new javax.swing.JTable();
        btn_lapPembayaran = new javax.swing.JButton();

        setTitle("Laporan Pembayaran");

        cmbCari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tanggal", "Kode Asuransi", "Nomer Polis" }));

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        tblLapPemb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblLapPemb);

        btn_lapPembayaran.setText("Cetak Laporan");
        btn_lapPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lapPembayaranActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_lapPembayaran)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_lapPembayaran)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        String kolom = "";
        switch (cmbCari.getSelectedIndex()) {
            case 0:
                kolom = "tglPembayaran";
                break;
            case 1:
                kolom = "kodeAsuransi";
                break;
            case 2:
                kolom = "noPolis";
                break;
            default:
                throw new AssertionError();
        }
        pc.bindingLaporanPembayaran(tblLapPemb, header, kolom, txtCari.getText());

    }//GEN-LAST:event_btnCariActionPerformed

    private void btn_lapPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lapPembayaranActionPerformed
        // TODO add your handling code here:
        try {
                String path = "report/ReportPembayaran.jasper";  
                String driver="oracle.jdbc.OracleDriver";
                String konek="jdbc:oracle:thin:@localhost:1521:XE";
                String user="system";
                String password="root";
                HashMap parameter = new HashMap();
                Class.forName(driver);
                Connection conn = DriverManager.getConnection(konek,user,password);
                File reportFile=new File(path);
                InputStream jReport = this.getClass().getClassLoader().getResourceAsStream(reportFile.getPath());
//                JasperReport jReport = (JasperReport) JRLoader.loadObject(reportFile.getPath());
                JasperPrint jPrint = JasperFillManager.fillReport(jReport, parameter, conn);
                JasperViewer.viewReport(jPrint, true);
                JasperViewer.setDefaultLookAndFeelDecorated(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Laporan Tidak Dapat Dicetak!\n" + e.getMessage()
                ,"Cetak Laporan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_lapPembayaranActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btn_lapPembayaran;
    private javax.swing.JComboBox<String> cmbCari;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLapPemb;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
